"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta

from decouple import config, Csv
from dj_database_url import parse as db_url
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.urls import reverse_lazy

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY",
                    'xitx%3sr@ql^exkrgzj50!($xg^-57deww3&@v8y55+!89c6n4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default="*")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # rest-framework
    'rest_framework',
    'stdimage',

    'allauth',
    'allauth.account',
    # 'allauth.socialaccount',
    'dj_rest_auth.registration',

    # apps
    'apps.user',
]

if DEBUG:
    INSTALLED_APPS += ["django_extensions"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = True

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

_DEFAULT_DB = "sqlite:///" + os.path.join(BASE_DIR, "db.sqlite3")

DATABASES = {
    "default": config("DATABASE_URL", default=_DEFAULT_DB, cast=db_url)
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# ========================= USER CONFIGURATION ============================== #
AUTHENTICATION_BACKENDS = [
    'authenticate.backend.ModelBackend',
]

# Tell Django about the custom `User` model we created. The string
# `authentication.User` tells Django we are referring to the `User` model in
# the `authentication` module. This module is registered above in a setting
# called `INSTALLED_APPS`.
AUTH_USER_MODEL = 'user.User'

# Authentication configuration
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'email'

AVATAR_GRAVATAR_DEFAULT = 'mp'
AVATAR_GRAVATAR_FORCEDEFAULT = True
AVATAR_MAX_AVATARS_PER_USER = 1
AVATAR_DEFAULT_URL = 'assets/img/generic_avatar.png'
AVATAR_AUTO_GENERATE_SIZES = [65, 80, 180]

AVATAR_MAX_SIZE = 4096
# ============================ VALIDATORS =================================== #
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================ FIXTURES ===================================== #
FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'project', 'fixtures'),
]
# ============================= DRF ========================================= #
REST_FRAMEWORK = {
    # if you want with milliseconds or
    'DATETIME_FORMAT': '%s',
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'djangorestframework_camel_case.parser.CamelCaseJSONParser'
    ]
}

# ========================= JWT Authenticate configure  ====================== #
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'wind-account'  # Name of cookie in auth request JWT

REST_AUTH_SERIALIZERS = {
    'JWT_TOKEN_CLAIMS_SERIALIZER': 'authenticate.jwt.TokenObtainPairSerializer'
}

token_life_time = timedelta(
    minutes=config('AUTHENTICATION_TOKEN_LIFETIME', cast=int, default=5)
)

private_key = config('PRIVATE_AUTHENTICATION_KEY')
public_key = config('PUBLIC_AUTHENTICATION_KEY')

SIMPLE_JWT = {
    'USER_ID_FIELD': 'uuid',
    'ACCESS_TOKEN_LIFETIME': token_life_time,
    'VERIFYING_KEY': public_key if not os.path.isfile(public_key) else open(public_key, 'rb').read(),
    'SIGNING_KEY': private_key if not os.path.isfile(private_key) else open(private_key, 'rb').read(),
    'ALGORITHM': 'RS256',
}


# =============================== CELERY ==================================== #
# CELERY
CELERY_BROKER_URL = 'amqp://{user}:{password}@{server}:5672/'.format(
    user=config('CELERY_USER', default='admin', cast=str),
    password=config('CELERY_PASSWORD', default='admin', cast=str),
    server=config('CELERY_SERVER', default='localhost', cast=str),
)

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE

# =============================== HEROKU ==================================== #
if config('HEROKU', cast=bool, default=False):
    import django_heroku
    django_heroku.settings(locals())

    # ================= Configuração do Storage ================================
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')  # Key do usuário de acesso
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')  # Chave do usuário de acesso
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')  # Nome do Bucket
    AWS_LOCATION = 'account-clientize'
