# Generated by Django 3.0.8 on 2020-07-30 05:31

import apps.avatar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gravatar', 'Gravatar'), ('internal', 'Internal')], default='internal', max_length=8, verbose_name='type')),
                ('image', stdimage.models.StdImageField(blank=True, help_text='Avatars should be sent by mininum of 640px largura x 480px altura.(png/jpg)', max_length=500, null=True, upload_to=apps.avatar.models.get_image_path, validators=[stdimage.validators.MinSizeValidator(640, 480), stdimage.validators.MaxSizeValidator(1400, 1861)], verbose_name='imagem principal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
    ]
