# Generated by Django 3.0.8 on 2020-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='main',
            field=models.BooleanField(blank=True, default=False, verbose_name='main'),
        ),
    ]
